//! Cumulative royalty earnings tracking.
//!
//! Tracks the total amount of royalty earnings generated by each NFT.
//!
//! # Storage
//! Key: `DataKey::RoyaltyEarnings(TokenId)` → `i128` (persistent)

use soroban_sdk::Env;

use crate::types::{DataKey, Error, TokenId};

/// Retrieve the cumulative royalty earnings for a token.
/// Returns `0` if no earnings have been recorded yet.
pub fn get_cumulative_earnings(env: &Env, token_id: TokenId) -> i128 {
    env.storage()
        .persistent()
        .get(&DataKey::RoyaltyEarnings(token_id))
        .unwrap_or(0)
}

/// Increment the cumulative royalty earnings for a token.
/// Prevents overflow by returning an error if the increment would exceed `i128::MAX`.
pub fn increment_earnings(env: &Env, token_id: TokenId, amount: i128) -> Result<(), Error> {
    if amount < 0 {
        return Err(Error::InvalidSalePrice);
    }

    let current = get_cumulative_earnings(env, token_id);
    let new_total = current.checked_add(amount).ok_or(Error::RoyaltyOverflow)?;

    env.storage()
        .persistent()
        .set(&DataKey::RoyaltyEarnings(token_id), &new_total);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_to_zero() {
        let env = Env::default();
        assert_eq!(get_cumulative_earnings(&env, 1), 0);
    }

    #[test]
    fn increments_correctly() {
        let env = Env::default();
        increment_earnings(&env, 1, 100).unwrap();
        assert_eq!(get_cumulative_earnings(&env, 1), 100);

        increment_earnings(&env, 1, 50).unwrap();
        assert_eq!(get_cumulative_earnings(&env, 1), 150);
    }

    #[test]
    fn prevents_overflow() {
        let env = Env::default();
        increment_earnings(&env, 1, i128::MAX - 10).unwrap();

        let result = increment_earnings(&env, 1, 11);
        assert_eq!(result, Err(Error::RoyaltyOverflow));
    }

    #[test]
    fn rejects_negative_amounts() {
        let env = Env::default();
        let result = increment_earnings(&env, 1, -50);
        assert_eq!(result, Err(Error::InvalidSalePrice));
    }
}
